export const tableData = [
  {
    id: "AMC",
    name: "AMC Entertainment Holdings, Inc",
    noCell1: 0,
    noCell2: 7,
    noCell3: 3.4,
    ddCell1: "standard",
    ddCell2: "medium",
  },
  {
    id: "AGNC",
    name: "AGNC Investment Corp.",
    noCell1: 9.34,
    noCell2: 14,
    noCell3: 2,
    ddCell1: "standard",
    ddCell2: "medium",
  },
  {
    id: "ABBV",
    name: "AbbVie Inc.",
    noCell1: 4.98,
    noCell2: 21,
    noCell3: 2,
    ddCell1: "",
    ddCell2: "medium",
  },
  {
    id: "ARCC",
    name: "Ares Capital Corporation - Clos",
    noCell1: 9.66,
    noCell2: 15,
    noCell3: 1.7,
    ddCell1: "standard",
    ddCell2: "",
  },
  {
    id: "ATVI",
    name: "Activision Blizzard, Inc",
    noCell1: 0.45,
    noCell2: 32,
    noCell3: 2,
    rhNOfAnalysts: 31,
    rhBuy: 87,
    rhHold: 10,
    rhSell: 3,
    rhgStarRating: "2",
    ddCell1: "standard",
    ddCell2: "high",
    rhgFairVal: 73,
  },
  {
    id: "AVGO",
    name: "Broadcom Inc.",
    noCell1: 3.31,
    noCell2: 28,
    noCell3: 1.9,
    ddCell1: "standard",
    ddCell2: "medium",
  },
  {
    id: "BABA",
    name: "Alibaba Group Holding Limited",
    noCell1: 0,
    noCell2: 47,
    noCell3: 1.6,
    ddCell1: "poor",
    ddCell2: "high",
  },
  {
    id: "BKR",
    name: "Baker Hughes Company",
    noCell1: 3.35,
    noCell2: 26,
    noCell3: 2,
    ddCell1: "standard",
    ddCell2: "high",
  },
  {
    id: "BP",
    name: "BP p.l.c.",
    noCell1: 5.8,
    noCell2: 10,
    noCell3: 2.2,
    ddCell1: "standard",
    ddCell2: "high",
  },
  {
    id: "BXP",
    name: "Boston Properties, Inc.",
    noCell1: 4.08,
    noCell2: 18,
    noCell3: 2.5,
    ddCell1: "exemplary",
    ddCell2: "high",
  },
  {
    id: "CODX",
    name: "Co-Diagnostics, Inc.",
    noCell1: 0,
    noCell2: 3,
    noCell3: 2,
    ddCell1: "exemplary",
    ddCell2: "high",
  },
  {
    id: "CPE",
    name: "Callon Petroleum Company",
    noCell1: 0,
    noCell2: 16,
    noCell3: 3,
    ddCell1: "exemplary",
    ddCell2: "high",
  },
  {
    id: "CRM",
    name: "Salesforce.com Inc",
    noCell1: 0,
    noCell2: 39,
    noCell3: 1.9,
    ddCell1: "standard",
    ddCell2: "medium",
  },
  {
    id: "CSCO",
    name: "Cisco Systems, Inc.",
    noCell1: 3.17,
    noCell2: 21,
    noCell3: 2.4,
    ddCell1: "standard",
    ddCell2: "medium",
  },
  {
    id: "CVX",
    name: "Chevron Corporation",
    noCell1: 5.92,
    noCell2: 25,
    noCell3: 2.3,
    ddCell1: "exemplary",
    ddCell2: "high",
  },
];
