export const tableData = [
  {
    id: "AMC",
    name: "AMC Entertainment Holdings, Inc",
    noCell1: 0,
    noCell2: 7,
    noCell3: 3.4,
    rhNOfAnalysts: 9,
    rhBuy: 0,
    rhHold: 67,
    rhSell: 33,
    rhgFairVal: null,
  },
  {
    id: "AGNC",
    name: "AGNC Investment Corp.",
    noCell1: 9.34,
    noCell2: 14,
    noCell3: 2,
    rhNOfAnalysts: 13,
    rhBuy: 77,
    rhHold: 23,
    rhSell: 0,
    rhgFairVal: null,
  },
  {
    id: "ABBV",
    name: "AbbVie Inc.",
    noCell1: 4.98,
    noCell2: 21,
    noCell3: 2,
    rhNOfAnalysts: 20,
    rhBuy: 70,
    rhHold: 30,
    rhSell: 0,
    rhgStarRating: "3",
    ddCell1: "standard",
    ddCell2: "medium",
    rhgFairVal: 97,
  },
  {
    id: "ARCC",
    name: "Ares Capital Corporation - Clos",
    noCell1: 9.66,
    noCell2: 15,
    noCell3: 1.7,
    rhNOfAnalysts: 14,
    rhBuy: 93,
    rhHold: 7,
    rhSell: 0,
    rhgFairVal: null,
  },
  {
    id: "ATVI",
    name: "Activision Blizzard, Inc",
    noCell1: 0.45,
    noCell2: 32,
    noCell3: 2,
    rhNOfAnalysts: 31,
    rhBuy: 87,
    rhHold: 10,
    rhSell: 3,
    rhgStarRating: "2",
    ddCell1: "standard",
    ddCell2: "high",
    rhgFairVal: 73,
  },
  {
    id: "AVGO",
    name: "Broadcom Inc.",
    noCell1: 3.31,
    noCell2: 28,
    noCell3: 1.9,
    rhNOfAnalysts: 32,
    rhBuy: 84,
    rhHold: 16,
    rhSell: 0,
    rhgStarRating: "2",
    ddCell1: "standard",
    ddCell2: "medium",
    rhgFairVal: 350,
  },
  {
    id: "BABA",
    name: "Alibaba Group Holding Limited",
    noCell1: 0,
    noCell2: 47,
    noCell3: 1.6,
    rhNOfAnalysts: 56,
    rhBuy: 96,
    rhHold: 4,
    rhSell: 0,
    rhgStarRating: "3",
    ddCell1: "poor",
    ddCell2: "high",
    rhgFairVal: 296,
  },
  {
    id: "BKR",
    name: "Baker Hughes Company",
    noCell1: 3.35,
    noCell2: 26,
    noCell3: 2,
    rhNOfAnalysts: 29,
    rhBuy: 83,
    rhHold: 17,
    rhSell: 0,
    rhgStarRating: "4",
    ddCell1: "standard",
    ddCell2: "high",
    rhgFairVal: 26,
  },
  {
    id: "BP",
    name: "BP p.l.c.",
    noCell1: 5.8,
    noCell2: 10,
    noCell3: 2.2,
    rhNOfAnalysts: 29,
    rhBuy: 62,
    rhHold: 28,
    rhSell: 10,
    rhgStarRating: "4",
    ddCell1: "standard",
    ddCell2: "high",
    rhgFairVal: 35,
  },
  {
    id: "BXP",
    name: "Boston Properties, Inc.",
    noCell1: 4.08,
    noCell2: 18,
    noCell3: 2.5,
    rhNOfAnalysts: 19,
    rhBuy: 58,
    rhHold: 42,
    rhSell: 0,
    rhgStarRating: "3",
    ddCell1: "exemplary",
    ddCell2: "high",
    rhgFairVal: 103,
  },
  {
    id: "CODX",
    name: "Co-Diagnostics, Inc.",
    noCell1: 0,
    noCell2: 3,
    noCell3: 2,
    rhgFairVal: null,
  },
  {
    id: "CPE",
    name: "Callon Petroleum Company",
    noCell1: 0,
    noCell2: 16,
    noCell3: 3,
    rhNOfAnalysts: 18,
    rhBuy: 17,
    rhHold: 56,
    rhSell: 28,
    rhgFairVal: null,
  },
  {
    id: "CRM",
    name: "Salesforce.com Inc",
    noCell1: 0,
    noCell2: 39,
    noCell3: 1.9,
    rhNOfAnalysts: 42,
    rhBuy: 88,
    rhHold: 10,
    rhSell: 2,
    rhgStarRating: "3",
    ddCell1: "standard",
    ddCell2: "medium",
    rhgFairVal: 253,
  },
  {
    id: "CSCO",
    name: "Cisco Systems, Inc.",
    noCell1: 3.17,
    noCell2: 21,
    noCell3: 2.4,
    rhNOfAnalysts: 26,
    rhBuy: 50,
    rhHold: 50,
    rhSell: 0,
    rhgStarRating: "3",
    ddCell1: "standard",
    ddCell2: "medium",
    rhgFairVal: 48,
  },
  {
    id: "CVX",
    name: "Chevron Corporation",
    noCell1: 5.92,
    noCell2: 25,
    noCell3: 2.3,
    rhNOfAnalysts: 26,
    rhBuy: 65,
    rhHold: 31,
    rhSell: 4,
    rhgStarRating: "4",
    ddCell1: "exemplary",
    ddCell2: "high",
    rhgFairVal: 111,
  },
];
